# Form implementation generated from reading ui file 'queue.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_selectImage(object):
    def setupUi(self, selectImage):
        selectImage.setObjectName("selectImage")
        selectImage.resize(221, 831)
        self.scrollArea = QtWidgets.QScrollArea(selectImage)
        self.scrollArea.setGeometry(QtCore.QRect(-1, 9, 221, 811))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 219, 809))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -1, 221, 821))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(1, 0, 0, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(selectImage)
        QtCore.QMetaObject.connectSlotsByName(selectImage)

    def retranslateUi(self, selectImage):
        _translate = QtCore.QCoreApplication.translate
        selectImage.setWindowTitle(_translate("selectImage", "Выбранные изображения"))
        self.label.setText(_translate("selectImage", "woiqwnoifoqiw"))
